### ISSUE TITLE
Cannot create instance of \Mailjet\Client while API key is NULL

### ISSUE THREAD

**Issue by mourareaupro** [mailjet/laravel-mailjet#10]
Hello i tried to use Mailjet as a new driver but i get this exception when i try to send a mail. 

I configured .env , mail.php , services.php 

I really need to send mails like this :  `Mail::to('test.pro@gmail.com')->send(new MassiveEmail($subject , $bodyMessage , $files));`

Because i use markdown. 

Let me know where i'm doing wrong 

Thanks in advance

**Comment by Nightbr** [comment]
What is the exception?

Add to that, I don't think we handle markdown Laravel interface for Mail.

**Comment by mourareaupro** [comment]
>  Swift_TransportException
> Cannot create instance of \Mailjet\Client while API key is NULL

**Comment by Nightbr** [comment]
It's pretty explicit I think you have not set your API key properly

**Comment by mourareaupro** [comment]
Here my controller : 

> public function postSendMassive(Request $request){
> 
>         $emails = Structure::where('type_structure_id', 4)->pluck('adresse_email_structure');
> 
>         $subject = $request->subject;
>         $bodyMessage = $request->texte;
> 
>         foreach($request->uploads as $file) {
>             $files[] = [
>                 'file' => $file->getRealPath(),
>                 'options' => [
>                     'mime' => $file->getClientMimeType(),
>                     'as'    => $file->getClientOriginalName()
>                 ],
>             ];
>         }
> 
>         Mail::to('mourareau.mathieu.pro@gmail.com')->send(new MassiveEmail($subject , $bodyMessage , $files));
> 
>         return back()->with('status', "Email envoyé");
>     }

**Comment by mourareaupro** [comment]
I know but i set the api key to .env , configured mail.php and services.php i don't know what more i need to do with the config :(

**Comment by Nightbr** [comment]
Follow step by step the installation guide: https://github.com/mailjet/laravel-mailjet#installation

It works well in all my project

**Comment by mourareaupro** [comment]
I followed this instructions. In your projects you use Mail:: facade to send mails ?

**Comment by Nightbr** [comment]
`Mail::to(config('mail.toAdress'))->send(new Contact($request->input('message'), $request->input('mail')));`

With a specific mail class https://laravel.com/docs/5.5/mail#writing-mailables

```php

<?php

namespace App\Mail;

use Illuminate\Bus\Queueable;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;
use Illuminate\Contracts\Queue\ShouldQueue;

class Contact extends Mailable
{
    use Queueable, SerializesModels;

    private $mailMessage;
    private $mailAdress;

    /**
     * Create a new message instance.
     *
     * @return void
     */
    public function __construct($mailMessage, $mailAdress)
    {
        $this->mailMessage = $mailMessage;
        $this->mailAdress = $mailAdress;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->view('emails.contact', array(
            'mailMessage' => $this->mailMessage,
            'mailAdress' => $this->mailAdress
        ));
    }
}
```

I don't know how markdown mailable works.

I think you should use SMTP transport with your mailjet account if you don't want to use specific API parameters (such as Transactionnal template, ...).

**Comment by Nightbr** [comment]
closed this, feel free to reopen this issue if you still have problem with markdown.

**Comment by zackarydev** [comment]
This is happening to me with the latest version.
