### ISSUE TITLE
Transactionnal variables

### ISSUE THREAD

**Issue by kahunafr** [mailjet/laravel-mailjet#11]
How to send variables to the transactionnal template?

**Comment by Nightbr** [comment]
Hey, look here: https://github.com/mailjet/MailjetSwiftMailer

This package use SwiftMailer and we have created a separate project to use it in non-laravel project.

You can also look at example in documentation, I'm pretty there is an example of what you're looking for: https://mailjet.github.io/laravel-mailjet/usage/

And in the developer guide: https://dev.mailjet.com/guides/#personalisation-v3

**Comment by kahunafr** [comment]
Thanks for your answer, but with https://github.com/mailjet/laravel-mailjet it's impossible to send personnals variable into template?

**Comment by Nightbr** [comment]
Yep sure you can do all the API can do

**Comment by kahunafr** [comment]
Like that:
`
        $body = ['Messages' => [
            [
              'FromEmail' => "test@website.com",
              'Recipients' => [
                  [
                    "Email" => "me@icloud.com"
                  ]
              ],
              'TemplateLanguage' => true,
              'MJ-TemplateID' => $ID,
              'Subject' => "TEST",
              'Variables' => json_decode('{
                  "link": $url
                }', true),
            ]
          ]];
        $response =  $mj->post(Resources::$Email, ['body' => $body]);`
For a {{var:link}} into template ?

**Comment by Nightbr** [comment]
Try to set up a project and test by yourself, this should work.

I'm sorry but I have no time to look further right now.

**Comment by kahunafr** [comment]
It does not work, that's my problem.

**Comment by Nightbr** [comment]
@Zhivko-Mailjet Hey, we need support here ty ;)

@kahunafr You need to give us more info (what is your code? what is the error (more than it doesn't work). Add to that if you're using the APi V3 (and not the API V3.1) it's not `Variables` but `Vars`. Please read the documentation https://dev.mailjet.com/guides/#personalisation-v3

**Comment by Zhivko-Mailjet** [comment]
@kahunafr 
Indeed, try using `Vars` instead of `Variables`.
Also. try with `'MJ-TemplateLanguage' => true` instead of `'TemplateLanguage' => true`

**Comment by kahunafr** [comment]
Here my code : https://codepaste.net/e4aann
This code send the mail, but doesn't transmit the variable. On the mail, i see {{var:link}} and not http://www.google.fr
I do not know if it's clear enough, do you need more information?

**Comment by kahunafr** [comment]
Thank you @Zhivko-Mailjet now it's ok!
Thanks also to @Nightbr
