### ISSUE TITLE
Support for Laravel 5.6

### ISSUE THREAD

**Issue by olivM** [mailjet/laravel-mailjet#12]
Would be great to have support for 5.6
Anyone know a fork, before i create one by myself ?

**Comment by philippkreis** [comment]
I need it as well - any solution out there?

**Comment by ocracy** [comment]
+1

**Comment by novocent** [comment]
+1

**Comment by Nightbr** [comment]
ping @mailjet/dev-evangelist

**Comment by olivM** [comment]
i'm trying to create a package with my current solution.
hope to be published next week

**Comment by Nightbr** [comment]
You can fork this package and create a PR to support 5.6

**Comment by philippkreis** [comment]
Hi guys, any news? If somebody has a solution you could also post what to change. 
Many thanks!

**Comment by ocracy** [comment]
Hi Philipp,

You can copy Mailjet\LaravelMailjet and Mailjet\MailjetSwiftMailer\SwiftMailer directories to any folder you want, then you should edit autoload section of composer.json like this

I copied to vendor_local folder.

"autoload": {
        "classmap": [
           *
        ],
        "psr-4": {
            "App\\": "app/",
            **"Mailjet\\LaravelMailjet\\": "vendor_local/laravel-mailjet/src",**
            **"Mailjet\\MailjetSwiftMailer\\SwiftMailer\\": "vendor_local/mailjet-swiftmailer/SwiftMailer"**
        }
    },

That is all.

**Comment by olivM** [comment]
Hi,

I finally managed to publish a first release my mail-transport package : https://github.com/Mahi-Mahi/mailjet-transport
Still working on documentation...
(and struggling with tests)

All comments, PR, ... are welcome !

**Comment by Nightbr** [comment]
This is pretty sad... @mailjet/dev-evangelist

**Comment by latanasov** [comment]
@maxchampoux  ( Mailjet API Product Manager), I am very  disappointed to see that after my departure from the company the support of[ laravel-mailjet](https://github.com/mailjet/laravel-mailjet) (4 697 installs) and [MailjetSwiftMailer](https://github.com/mailjet/MailjetSwiftMailer) ( 26 538 installs) is completely abandoned. 

Both are very successful **community driven**  projects and deserve attention.

**Comment by Choufourax** [comment]
We need support to for Laravel 5.6 too

**Comment by dmassiani** [comment]
+1

**Comment by ibnuhalimm** [comment]
+1

**Comment by cephee** [comment]
+1

**Comment by pfaffenrodt** [comment]
I see a lot of forks that updated composer to support 5.6. 
But no one created a pull request. Why?

**Comment by Nightbr** [comment]
Seems to be relative to this... https://github.com/mailjet/laravel-mailjet/issues/8
To my part, I have no spare time to maintain this repository and I'm not using Laravel in my current project. **I can help on some issue and answer some technical question** but the better thing to do if you want to see a feature is to create a PR and ping the mailjet dev team here or by mail.

**Comment by pfaffenrodt** [comment]
ping @Nightbr 
@mailjet 

dont know how to ping mailjet team

**Comment by Nightbr** [comment]
ping @mailjet/dev-evangelist

**Comment by Nightbr** [comment]
ping @maxchampoux

**Comment by latanasov** [comment]
@eboisgon lets do this, let me know if you need any assistance.

**Comment by mskochev** [comment]
Compatibility with Laravel 5.6 should be fine with the current version of the wrapper, so I'm closing this issue.
