### ISSUE TITLE
Add support for Laravel 5.7

### ISSUE THREAD

**Issue by Kaishiyoku** [mailjet/laravel-mailjet#18]

**Comment by inpakeo** [comment]
+++

**Comment by nasirouwagana** [comment]
Same thing for me. Please when upgrade for Laravel 5.7 will be ready

**Comment by phebsoftdev** [comment]
i have been waiting for upgrade. please make it compatible with 5.7

**Comment by developcreativo** [comment]
i have been waiting for upgrade. please make it compatible with 5.8?

**Comment by aliuygur** [comment]
+1

**Comment by myorb** [comment]
+1

**Comment by yagrasdemonde** [comment]
You can see this https://github.com/mailjet/laravel-mailjet/issues/20#issuecomment-487597084

**Comment by timvandenhende** [comment]
+1

**Comment by pihlersimon** [comment]
+ 1 !

**Comment by Kaishiyoku** [comment]
> You can see this [#20 (comment)](https://github.com/mailjet/laravel-mailjet/issues/20#issuecomment-487597084)

Of course I could just make a fork. But is this now the solution? That everyone makes a fork? We could make a *single* fork which everyone could use.

**Comment by uavn** [comment]
Should work now
