### ISSUE TITLE
Add support for Laravel 5.8

### ISSUE THREAD

**Issue by Kaishiyoku** [mailjet/laravel-mailjet#20]

**Comment by pathros** [comment]
composer require mailjet/laravel-mailjet

Installation failed, reverting ./composer.json to its original content.

**Comment by joeljerushan** [comment]
![image](https://user-images.githubusercontent.com/10111309/56078113-d7340680-5e01-11e9-9d1f-1f938c69395c.png)

We need support to Laravel 5.8 ...

**Comment by yagrasdemonde** [comment]
If you want install laravel-mailjet in **_laravel >= 5.5_**, you have to do some changes in your `composer.json.`

This is a mini guide : 

You can fork on your github account this repository, then edit on your fresh forked, in the **laravel5.5** Branch the `composer.json` file :

Change the value of laravel like this 
```json
"laravel/framework": "5.8.*",
```
Then in your project, edit your `composer.json`
Add
```json
"repositories": [
        {
          "type": "vcs",
          "url": "https://github.com/{YOURACCOUNT}/laravel-mailjet"
        }
     ],
```
And add in your require array of `composer.json`
```json
"mailjet/laravel-mailjet": "dev-laravel5.5",
```
Finally, run `composer update`, and laravel mailjet should begin install.
Enjoy !!

**Comment by skalero01** [comment]
Its easier if we use yagrasdemonde version :D 

Just edit your composer.json and add

```
"repositories": [
        {
          "type": "vcs",
          "url": "https://github.com/yagrasdemonde/laravel-mailjet"
        }
     ],
```

And add in your require array of composer.json

`"mailjet/laravel-mailjet": "dev-laravel5.5",`

**Comment by rvulpescu** [comment]
+1

**Comment by uavn** [comment]
Should work now
