### ISSUE TITLE
Support for Laravel 6.0

### ISSUE THREAD

**Issue by raulsh** [mailjet/laravel-mailjet#23]
Hi,

Laravel 6.0 it's not supported right now.

**Comment by kcassam** [comment]
this PR should maybe be merged : https://github.com/mailjet/laravel-mailjet/pull/22 @mskochev @mitomitov  ?

**Comment by luigi-13** [comment]
Hi, any news ?

**Comment by zorgzerg** [comment]
Guys, please!!!

**Comment by kevinschenkers** [comment]
Would really be appreciated!

**Comment by djoo** [comment]
+1

**Comment by ultimateBusiness** [comment]
+1

**Comment by tobias-schoenfleisch** [comment]
+1

**Comment by pihlersimon** [comment]
+ 1 !

**Comment by Antoine87** [comment]
done in https://github.com/mailjet/laravel-mailjet/pull/22
