### ISSUE TITLE
typo in MailjetMailServiceProvider.php which prevents properly loading config settings

### ISSUE THREAD

**Issue by ramon-noordeloos** [mailjet/laravel-mailjet#24]
Hi!

I found a typo in your code which prevents that the configuration in services.php can be properly loaded. The typo is in MailjetMailServiceProvider.php on line 20 and 21:

`$call = $this->app['config']->get('services.mailjet.transactionnal.call', true);`
`$options = $this->app['config']->get('services.mailjet.transactionnal.options', array());`

services.mailjet.transactio**nn**al.call should be services.mailjet.transactio**n**al.call (single 'n'). 

Because of this v3 is always used instead of v3.1.

Best regards, Ramon

**Comment by uavn** [comment]
fixed
