### ISSUE TITLE
How to add a contact to a list

### ISSUE THREAD

**Issue by djoo** [mailjet/laravel-mailjet#25]
Hi,

I try to use this SDK and i'm doing this to add a contact in a list :

```
use Mailjet\LaravelMailjet\Facades\Mailjet;

  $mj = Mailjet::getClient();
  $response =  $mj->createContact($body);
```

I have this error 
```
Symfony\Component\Debug\Exception\FatalThrowableError
Call to undefined method Mailjet\Client::createContact()
```

How can i call the method createContact ? 
Thanks

**Comment by uavn** [comment]
@djoo 
You should call createContact method from Mailjet without calling getClient:

// see MailjetService class to see all available methods

```
$response = Mailjet::createContact([
    'IsExcludedFromCampaigns' => "true",
    'Name' => "New Contact",
    'Email' => "passenger2@mailjet.com"
]);
```

also, you can use 'low-level' way (and here you'll need to call getClient):

```
$body = [
    'IsExcludedFromCampaigns' => "true",
    'Name' => "New Contact",
    'Email' => "passenger@mailjet.com"
];
$mg = MailJet::getClient();
$response = $mj->post(Resources::$Contact, ['body' => $body]);
```

**Comment by nibblebits** [comment]
That doesn't answer his question. I also have the same question, this creates a contact how do you get it in the list.

**Comment by uavn** [comment]
@nibblebits See 'Add a contact to a contact list' section at https://dev.mailjet.com/email/guides/contact-management/
