### ISSUE TITLE
Add support with Laravel 6.x

### ISSUE THREAD

**Issue by deshiloh** [mailjet/laravel-mailjet#26]
Hi !

Here the error message when i'm trying to install laravel-mailjet : 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Can only install one of: laravel/tinker[1.x-dev, v2.1.0].
    - Can only install one of: laravel/tinker[v2.1.0, 1.x-dev].
    - Can only install one of: laravel/tinker[1.x-dev, v2.1.0].
    - mailjet/laravel-mailjet 2.1.0 requires laravel/tinker ~1.0 -> satisfiable by laravel/tinker[1.x-dev].
    - Installation request for mailjet/laravel-mailjet ^2.1 -> satisfiable by mailjet/laravel-mailjet[2.1.0].
    - Installation request for laravel/tinker (locked at v2.1.0, required as ^2.0) -> satisfiable by laravel/tinker[v2.1.0].
```
for the moment i downgrade tinker with : 
``` 
"laravel/tinker": "^1",
```

**Comment by Pixa1** [comment]
To overcome this problems i added this to my composer.json
    "repositories": [
        {
          "type": "vcs",
          "url": "https://github.com/TheDoctor0/laravel-mailjet"
        }
     ],
 "require": {
     ...
    "mailjet/laravel-mailjet": "dev-master"
 }
and then composer update

**Comment by TheDoctor0** [comment]
As I do not like using dev forks in production and I am tired of waiting for my PR to be merged, 
I created my own package: [laravel-mailjet-driver](https://github.com/TheDoctor0/laravel-mailjet-driver/releases).

**Comment by uavn** [comment]
Should work now
