### ISSUE TITLE
Cannot install mailjet on Laravel 7 / spark 10.0

### ISSUE THREAD

**Issue by cicampemu** [mailjet/laravel-mailjet#31]
I'm trying to install mailjet on a project using LAravel 7.0 and Spark 10.0 but I get the following error:

`Problem 1
    - Can only install one of: laravel/tinker[1.x-dev, v2.4.1].
    - Can only install one of: laravel/tinker[v2.4.1, 1.x-dev].
    - Can only install one of: laravel/tinker[1.x-dev, v2.4.1].
    - mailjet/laravel-mailjet 2.1.0 requires laravel/tinker ~1.0 -> satisfiable by laravel/tinker[1.x-dev].
    - Installation request for mailjet/laravel-mailjet ^2.1 -> satisfiable by mailjet/laravel-mailjet[2.1.0].
    - Installation request for laravel/tinker (locked at v2.4.1, required as ^2.0) -> satisfiable by laravel/tinker[v2.4.1].`

Here is my composer.json:

`"require": {
        "php": "^7.2.5",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^6.3",
        "laravel/framework": "^7.0",
        "laravel/tinker": "^2.0",
        "laravel/spark-aurelius": "~10.0",
        "laravel/ui": "^2.0",
        "ext-gd": "*"
    },`

Any idea how to fix it?

Thanks,

**Comment by AdrienV** [comment]
EDIT : 

Solution on another issue : https://github.com/mailjet/laravel-mailjet/issues/29#issuecomment-603291340
Use this package : https://github.com/TheDoctor0/laravel-mailjet-driver

**Comment by uavn** [comment]
Should work now
