### ISSUE TITLE
Latest Update Not Working

### ISSUE THREAD

**Issue by bldcaveman** [mailjet/laravel-mailjet#34]
Thanks for updating the package.
Unfortunately we still cannot work with it.

With a fresh version of Laravel I get:

  Problem 1
    - Can only install one of: laravel/tinker[1.x-dev, v2.5.0].
    - Can only install one of: laravel/tinker[v2.5.0, 1.x-dev].
    - Can only install one of: laravel/tinker[1.x-dev, v2.5.0].
    - mailjet/laravel-mailjet 2.1.0 requires laravel/tinker ~1.0 -> satisfiable by laravel/tinker[1.x-dev].
    - Installation request for mailjet/laravel-mailjet ^2.1 -> satisfiable by mailjet/laravel-mailjet[2.1.0].
    - Installation request for laravel/tinker (locked at v2.5.0, required as ^2.5) -> satisfiable by laravel/tinker[v2.5.0].

According to the main code tab none of the files have been updated recently and the update has been applied to 1.1.0 as opposed to 2.X so I'm wondering if the work was done on the wrong version or if the work needs to be merged in.

The changes marked in the latest only show 2 archives: https://github.com/mailjet/laravel-mailjet/releases/tag/1.1.1
But the code within there seems to be referring to an outdated Laravel.

**Comment by bldcaveman** [comment]
Additionally I tried using varying versions of Tinker but none of them work with this package.  Tinker 2.0 added support for L7 so Tinker 1.X would only work with 6 and below.

**Comment by uavn** [comment]
@bldcaveman I just created a release 2.1.1 for latest changes, this should fix your errors, can you try again in a few minutes?
https://github.com/mailjet/laravel-mailjet/releases/tag/2.1.1

**Comment by bldcaveman** [comment]
Thanks so far so good! Composer now works. Just about to try hooking it up.

**Comment by bldcaveman** [comment]
Hiya

Now am getting this error as reported here:

https://github.com/mailjet/laravel-mailjet/issues/29

**Comment by bldcaveman** [comment]
It's worth noting that in L7 they changed a few things.  Please see this video: https://www.youtube.com/watch?v=vcQD9tHy6Gg&feature=youtu.be

I have updated my mail.php config but still no luck.

Have you successfully sent email using Laravel 8 using this package?

**Comment by i-fail** [comment]
Same, getting **Unsupported mail transport [mailjet]** error

**Comment by uavn** [comment]
@bldcaveman @i-fail 
Thanks, update is ready, mail driver should also work now.

But you need to rename MAIL_DRIVER to MAIL_MAILER in your .env file
Also you need to add mail transport in config/mail.php:
```
'mailers' => [
    ...

    'mailjet' => [
        'transport' => 'mailjet',
    ],
],
```

then it will work.

README updated as well

**Comment by bldcaveman** [comment]
I can confirm I am now able to send emails 👍 :)
