### ISSUE TITLE
Cannot use the API to delete a contact

### ISSUE THREAD

**Issue by bldcaveman** [mailjet/laravel-mailjet#39]
When using `$response = Mailjet::delete(Resources::$Contact, ['id' => $ID` we get refused.

I can get around this with curl but notice that the endpoint url for delete is quite different (one uses 4 and the other 3 with REST):

https://api.mailjet.com/v3/REST/contact/$CONTACT_EMAIL
VS
https://api.mailjet.com/v4/contacts/{contact_ID}

**Comment by uavn** [comment]
@bldcaveman
I added possibility to remove a contact, but you need to do a few things:
- update your composer dependencies, so v**2.1.3** of laravel-mailjet will be downloaded;
- add 'v4' configuration section to your mailjet config:
```
'mailjet' => [
    ...
    'v4' => [
        'call' => true,
        'options' => [
            'url' => 'api.mailjet.com',
            'version' => 'v4',
            'call' => true,
            'secured' => true
        ]
    ],
]
```
- add \Mailjet\LaravelMailjet\Providers\ContactsServiceProvider::class, to your providers:
```
'providers' => [
    ...
    \Mailjet\LaravelMailjet\Providers\ContactsServiceProvider::class,
    ...
]
```
- use it:
```
public function handle(ContactsV4Service $contactsV4Service)
{
    $response = $contactsV4Service->delete(351406781);
    ...
}
```

I also updated https://github.com/mailjet/laravel-mailjet/blob/master/README.md with this example.

**Comment by stephenstack** [comment]
Hi,

The above is not working. Provider is registered, but class dependancy kicks in

   ArgumentCountError

  Too few arguments to function Mailjet\LaravelMailjet\Services\ContactsV4Service::__construct(), 0 passed in /var/www/html/www.rconfig.com/app/Console/Commands/MailJetTest.php on line 49 and exactly 1 expected

  at vendor/mailjet/laravel-mailjet/src/Services/ContactsV4Service.php:23
    19|
    20|     /**
    21|      * @param MailjetService $mailjet
    22|      */
  > 23|     public function __construct(MailjetService $mailjet)
    24|     {
    25|         $this->mailjet = $mailjet;
    26|     }
    27|

  1   app/Console/Commands/MailJetTest.php:49
      Mailjet\LaravelMailjet\Services\ContactsV4Service::__construct()
