### ISSUE TITLE
Send link parameter for campaign template

### ISSUE THREAD

**Issue by StefanijaK** [mailjet/laravel-mailjet#4]
I am trying to send a campaign template by its id in Laravel and in the template I have a button as a link, but I need to specify the link from Laravel. Could you please tell me if there is a way of doing this?
Thanks in advance,
Stefanija

**Comment by Zhivko-Mailjet** [comment]
@StefanijaK 
could you please elaborate more on what exactly you are trying to achieve ? What kind of a button you have and what kind of link you want to set from Laravel ? Are you trying to pass a variable with a link inside?

**Comment by StefanijaK** [comment]
@Zhivko-Mailjet first of all thank you for replay.
I need to implement a password reset functionality, so I will need to use a link and a button in order to send the url. When I insert a button I will need to send the link from Laravel. If a set a variable to the button how can I send the url/link value? Or is there any easier way to implement this?

**Comment by Zhivko-Mailjet** [comment]
@StefanijaK 
You can insert a variable, which will be included behind the button in the content, something like {{var:link}}. Syntax samples you can find here:
https://dev.mailjet.com/guides/#using-a-template

Other template samples you can find here:
https://github.com/mailjet/mailjet-apiv3-templating-samples/tree/master/samples

As the question is relatedto the template construction more than the Laravel usage, if you have additional questions, please reach out to our [support ](https://www.mailjet.com/support/ticket)and we will be happy to help.

**Comment by StefanijaK** [comment]
@Zhivko-Mailjet thank you so much for your help. I really appreciate it. Have a great day :)

**Comment by GaddMaster** [comment]
[ Learned that Hotmail does some kind of sanitizing and the links need start with protocol ]
This answer still appears to be unanswered.
How do I add a variable link to my button ?
Inside a button where the URL goes, variables don't work. I tried sticking in {{var:domain}}/token/{{var:token}}, but the resulting HTML is not a button. shows up HTML like so
"[www.google.ie]"
<span style="font-size:14px">Reset password</span>

Naturally when we google this, no hope, endless other things. This is the only thread on it. Searched all docs, nothing.

Also I tried copying and pasting code from the examples and they break the template, they don't work. Example [here](https://github.com/mailjet/mailjet-apiv3-templating-samples/blob/master/samples/ecommerce/template.html), the a tag link at bottom doesn't work for me like shown in this example.
<a href="{{ var:domain:"" }}">click here</a>
or 
<a href = "{{var:domain}}">Link</a>
stuck

Ideally I want to add a variable inside the link input box when using the button component.

Any help be great ?

**Comment by alfredozn** [comment]
Did you find a solution or workaround? I am stuck in the same situation.

Thanks

**Comment by ElieBoury** [comment]
I was stuck with the same problem and here is the solution : 
in order to put vars in links, you have to respect this : {{var:myvar}} and NO default value.

**Comment by TamaraGhazaryan** [comment]
I also have a problem sending link as a parameter value in mailjet template. 

**A template language occurred when sending a message using Template "": expression parsing error ## Access violation ## near ## {{var:confirmationLink: ##**

I'm not specifying any default value.

**Comment by alex-r89** [comment]
Why is this not documented anywhere obvious/at all....

**Comment by OlgaMaslova** [comment]
Hello, 
I am still struggling in putting a variable as href.
Tried:
href="{{var.:link}}"

Getting error: expression parsing error ## Unknown identifier: var:link ## near ## {{var:link ##

Any help, please?

**Comment by TamaraGhazaryan** [comment]
Hello OlMas,

You need to put variables without string quotes. So instead of
"{{var.:link}}" try {{var.:link}}.

**Comment by TamaraGhazaryan** [comment]
This is my example which works fine without string quotes
[image: image.png]
