### ISSUE TITLE
Question: New release for php 8 missing?

### ISSUE THREAD

**Issue by fachcraftim** [mailjet/laravel-mailjet#45]
Hi!

Looks like you guys already made the afford to make the code base working with php 8 - thanks for that!

@uavn  I can't find a release with a tag pointing to the latest changes - am I missing something here?

Thanks in advance!

Tim

**Comment by jp-resource** [comment]
Hi, 
Thank you for your efforts for PHP 8.  But I noticed that `fzaninotto/faker`. is abandoned and throws an error when installed on PHP8. Could you guys update this faker as well. Maybe with this `fakerphp/faker`. 
Thanks in advance.

**Comment by ikidnapmyself** [comment]
I just wanted to use mailjet package in a project what is currently under development, so I installed `dev-master` instead of a release. I had no error. 
`composer require mailjet/laravel-mailjet:dev-master`

otherwise with PHP 8.0.0:
```
composer require mailjet/laravel-mailjet        
Using version ^2.1 for mailjet/laravel-mailjet
./composer.json has been updated
Running composer update mailjet/laravel-mailjet
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mailjet/laravel-mailjet 2.1.0 requires laravel/tinker ~1.0 -> found laravel/tinker[v1.0.0, ..., 1.x-dev] but it conflicts with your root composer.json require (^2.5).
    - mailjet/laravel-mailjet[2.1.1, ..., 2.1.3] require php ^7.1.3 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires mailjet/laravel-mailjet ^2.1 -> satisfiable by mailjet/laravel-mailjet[2.1.0, 2.1.1, 2.1.2, 2.1.3].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by fachcraftim** [comment]
I've also installed dev-master, in addition to that I pointed to a specific commit to be sure nothing will break in the upcomping deployments

That's what I've done

`composer require mailjet/laravel-mailjet:dev-master#e168d36`

**Comment by uavn** [comment]
@fachcraftim @jp-resource @ikidnapmyself thanks
faker updated, release tag 3.0.0 added
