### ISSUE TITLE
Using the Subject Line from a Template

### ISSUE THREAD

**Issue by temp1029** [mailjet/laravel-mailjet#50]
I am trying to use the subject line from my template in an email. The problem is, if you don't provide a subject line to a Laravel Mailable, the following code creates a subject line based on the classname.

[`$message->subject(Str::title(Str::snake(class_basename($this), ' ')));`](https://github.com/laravel/framework/blob/70490255a2249045699d0c9878f9fe847ad659b3/src/Illuminate/Mail/Mailable.php#L394)

In addition, setting the subject line to a "truthy" value, results in it overriding the subject line on the template. I haven't been able to find a way around this, but if one exists I'd appreciate some advice.

**Comment by temp1029** [comment]
So I think I figured out a way to make this work, but the caveat is **you can't specify any subject line when using a template**. This is fine for my use-case but other's mileage might vary. Allowing this might need a config setting or an extra header to be set. Ideally Laravel would allow for empty subject lines, but that's unlikely.

Since this package is specific to Laravel I figured some special code to handle a Laravel oddity was OK.

In summary we just need to override the 'send' and 'bulkSend' functions in the [laravel-mailjet transport file](https://github.com/mailjet/laravel-mailjet/blob/master/src/Transport/MailjetTransport.php). This just looks for the 'X-MJ-TemplateID' header and removes the subject line if it is found. After removing the subject line it allows processing to proceed as normal.

The entire file should look like this:
```php
<?php

namespace Mailjet\LaravelMailjet\Transport;

use Mailjet\MailjetSwiftMailer\SwiftMailer\MailjetTransport as BaseTransport;

use \Swift_Mime_SimpleMessage;

class MailjetTransport extends BaseTransport
{
    public function send(Swift_Mime_SimpleMessage $message, &$failedRecipients = null)
    {
        if($message->getHeaders()->has('X-MJ-TemplateID'))
        {
            $message->setSubject(null);
        }

        return parent::send($message, $failedRecipients);
    }

    public function bulkSend(array $messages, &$failedRecipients = null)
    {
        foreach($messages as $message)
        {
            if($message->getHeaders()->has('X-MJ-TemplateID'))
            {
                $message->setSubject(null);
            }
        }

        return parent::bulkSend($messages, $failedRecipients);
    }
}
```

**Comment by oleksandr-mykhailenko** [comment]
Hello, we analyzed your solution. For now, it's too specific and we can't implement it as default, for all. But in the future, we will make an improvement to this area.
Thank you
