### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by TobiasGraml11** [mailjet/laravel-mailjet#51]
A new Laravel version was released, could you please add support for it?

![image](https://user-images.githubusercontent.com/51320851/153148435-6bdf4797-7c52-4893-8f07-a97d2b93aedf.png)

**Comment by gpanos** [comment]
There is a PR open for this already :)

**Comment by PetroSilenius** [comment]
This is the only thing blocking our upgrade so would be a great to get this through!😄

**Comment by amirilidan78** [comment]
same here :(

**Comment by zeefarmer** [comment]
Thanks for the feedback here, we've released a new version that supports Laravel 9
