### ISSUE TITLE
Tag 3.0.1 doesn't respect semantic versionning (introduce breaking change)

### ISSUE THREAD

**Issue by jdecool** [mailjet/laravel-mailjet#53]
The latest version ([3.0.1](https://github.com/mailjet/laravel-mailjet/releases/tag/3.0.1)) doesn't respect [semantic versionning](https://semver.org) and introduce a breaking change on a patch version.

PR #52 has removed the `src/MailjetMailServiceProvider.php` file which is, according to the documentation, required in the providers array (cf. https://github.com/mailjet/laravel-mailjet/blob/1878b0f716c6004a363836699dcfffa5d7efc0e0/README.md?plain=1#L28)

![image](https://user-images.githubusercontent.com/433926/156460654-b5542c04-3b40-46d8-bbea-368c8b1c44c9.png)

**Comment by Baser-T** [comment]
Is it possible that this is the reason why I'd get a 500 error on sending a verificationmail? as of the update after commenting the MailjetMailServiceProvider out I seem to get 500 error when sending mails towards mailjet.

**Comment by Pavlico** [comment]
#54 merged
