### ISSUE TITLE
Reply-to addresses

### ISSUE THREAD

**Issue by dave-smyth** [mailjet/laravel-mailjet#63]
We’re using Mailjet as the driver for Statamic. Emails are sending perfectly but however we define the `reply-to` email address, they don’t seem to feed through – replying always prefills to the sender’s email address.

We’ve used other drivers in the past where this functionality works. Is this something that can be set through this package? Or is it likely a configuration issue (either between laravel-mailjet and Statamic or at the account end)?

**Comment by oleksandr-mykhailenko** [comment]
Hello @websmyth 
So looks like something is mussing in configuration. But it's hard to answer for sure. Do you have an example of code that you're trying to execute ?

**Comment by dave-smyth** [comment]
Afraid not – this is from so long ago I’m not sure what project it’s even from. :)

I think we might have switched to SMTP instead. Thanks for getting back to me – I’ll close this now.
