### ISSUE TITLE
Inline attachments don't work

### ISSUE THREAD

**Issue by dicaccamovincenzo92** [mailjet/laravel-mailjet#66]
Hi,
using `$message->embed($pathToFile);` to embed an inline attached image, results in empty img tag on received email.
Is there any workaround? Could you add inline attachment compatibility to this package?

**Comment by oleksandr-mykhailenko** [comment]
hello @dicaccamovincenzo92 
did you put the full path to the image ? Because email requires a full path,
something like `<img src="{{ $message->embed(public_path() . '/images/image.jpg') }}" />`

**Comment by oleksandr-mykhailenko** [comment]
Please, read this documentation https://laravel.com/docs/10.x/mail

Int he library everything works fine
