### ISSUE TITLE
Laravel 10 not supported

### ISSUE THREAD

**Issue by ams-ryanolson** [mailjet/laravel-mailjet#68]
a new version is required to work with Laravel 10

**Comment by Radyum** [comment]
Composer output if it can help:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mailjet/laravel-mailjet 3.0.0 requires laravel/framework ~5.1|^6.0|^7.0|^8.0 -> found laravel/framework[v5.1.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27] but it conflicts with your root composer.json require (^10.0).
    - mailjet/laravel-mailjet[3.0.1, ..., 3.0.3] require laravel/framework ~5.1|^6.0|^7.0|^8.0|^9.0 -> found laravel/framework[v5.1.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but it conflicts with your root composer.json require (^10.0).
    - Root composer.json requires mailjet/laravel-mailjet ^3.0 -> satisfiable by mailjet/laravel-mailjet[3.0.0, 3.0.1, 3.0.2, 3.0.3].
```

**Comment by oleksandr-mykhailenko** [comment]
Hello @ams-ryanolson @Radyum 
I cloned repo and run `composer install`. It worked for me. Could you check it,please ?

**Comment by Radyum** [comment]
I tried:
- I removed my vendor folder and my composer.lock file
- I added this to my composer.json
```
"repositories": [
        {
            "url": "git@github.com:mailjet/laravel-mailjet.git",
            "type": "git"
        }
    ],
```
- I ran composer install

And I got the same error.

However I can see that the composer.json file has been updated here: https://github.com/mailjet/laravel-mailjet/commit/35be5f34a7cbbafe0787be19aad8d470e4eeed03

I think I did something wrong.

**Comment by oleksandr-mykhailenko** [comment]
@Radyum 
looks like you shouldn't add items like 

```
"repositories": [
        {
            "url": "git@github.com:mailjet/laravel-mailjet.git",
            "type": "git"
        }
    ],
```

instead try to add to required section it and run `composer install`

**Comment by azagoru** [comment]
Trying to make
composer require mailjet/laravel-mailjet
but still getting
    - mailjet/laravel-mailjet[3.0.1, ..., 3.0.3] require laravel/framework ~5.1|^6.0|^7.0|^8.0|^9.0 -> found laravel/framework[v5.1.0, ..., v5.8.38, v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0] but it conflicts with your root composer.json require (^10.0).

**Comment by oleksandr-mykhailenko** [comment]
So I run locally next command

![image](https://user-images.githubusercontent.com/9269550/219406486-e366ba8b-c932-460d-accd-ade4f35c6c26.png)

and everythung worked well

![image](https://user-images.githubusercontent.com/9269550/219407370-9f1df59a-4f40-4456-81f3-8ac0f1dc4708.png)


Do you make this command inside laravel ?

**Comment by blissgrn** [comment]
@oleksandr-mykhailenko : It seems that you are using laravel/framework v8.83.27, you need to upgrade laravel to v10 to see the error.

**Comment by Sotiris-k** [comment]
Hello,

The latest two PRs #67 #69 fix the laravel 10 support. Is there a problem with releasing a new version with these changes in?

**Comment by oleksandr-mykhailenko** [comment]
Hello @Sotiris-k 
So release was created. Thank you 
https://github.com/mailjet/laravel-mailjet/releases/tag/3.0.4
