### ISSUE TITLE
Is it possible to disable Mailjet Tracking when sending mails

### ISSUE THREAD

**Issue by gregoirebyvets** [mailjet/laravel-mailjet#71]
Is it possible to turn off mailjet tracking on specific mails (Mj-trackopen) ?

I can't find anything related to this in the documentation

**Comment by oleksandr-mykhailenko** [comment]
Hello @gregoirebyvets 
For each email it is not possible , only on account level.
But if you want to use something custom, you can use URL Tags, here is info 
https://dev.mailjet.com/email/guides/send-api-v31/#add-url-tags
