### ISSUE TITLE
Can't set the X-MJ-CustomID header

### ISSUE THREAD

**Issue by riiad** [mailjet/laravel-mailjet#73]
Hi,

I tried both the SMTP configuration and the Send API, but it looks like my emails does not have the X-MJ-CustomID header.

Here is an example of a mailable:

```php
public function build()
{
    $this->replyTo(...);

    $this->withSymfonyMessage(function (Message $message) {
        $message->getHeaders()->addTextHeader('X-MJ-CustomID', '...');

        return $message;
    });


    return $this
        ->subject('...')
        ->markdown('...')->with(...);
}

```

Am i doing something wrong ?

`Laravel 9` / `mailjet/laravel-mailjet:3.0.4`
Thanks

**Comment by riiad** [comment]
Anyone ?

**Comment by oleksandr-mykhailenko** [comment]
Hello @riiad 
According to the documentation ( https://symfony.com/doc/6.0/mailer.html#creating-sending-messages ) everything looks correct. Just try to debug and show how your headers were built

**Comment by oleksandr-mykhailenko** [comment]
Close due to inactivity
