### ISSUE TITLE
missing symfony/http-client dependency

### ISSUE THREAD

**Issue by lsmith77** [mailjet/laravel-mailjet#75]
see https://github.com/symfony/mailer/blob/7.0/Transport.php#L40C34-L40C53

**Comment by lsmith77** [comment]
looks like this previous ticket was closed erroneously https://github.com/mailjet/laravel-mailjet/issues/56

dependencies should be explicit.

**Comment by oleksandr-mykhailenko** [comment]
Hello
This one is updated
