### ISSUE TITLE
Wrong composer.json versions since v3.0.1 (swift vs symfony)

### ISSUE THREAD

**Issue by mortenscheel** [mailjet/laravel-mailjet#77]
In version 3.0.1 this package switched from Swift to Symfony transports, without updating the required version of `laravel/framework`.

Laravel switched to Symfony mail in v9.0, which means that `mailjet/laravel-mailjet`  v3.0.1+ can't be used used in Laravel projects using Laravel version < 9.0.

Please fix this by changing the laravel/framework requirement to `^9.0|^10.0|^11.0` in the releases that use symfony.

I don't know if it's possible to fix the releases that have already been published, but in any case you should add a note in the readme and documentation, explaining which version to install if you're using laravel <9.0.

**Comment by oleksandr-mykhailenko** [comment]
Thank you. This one is fixed
