### ISSUE TITLE
No exceptions / errors thrown on config error

### ISSUE THREAD

**Issue by justrustyspoons** [mailjet/laravel-mailjet#78]
I had a frustrating morning trying to get Mailjet to work, it was reporting emails as being sent, I was getting a success message, but in reality it never sent and was rejected by the API

I switched to another provider and lo and behold there was the error, I had not configured the from address to be an address of the registered domain

After updating the setting Mailjet worked

Could the library somehow actually report the error rather than giving a false positive?

**Comment by oleksandr-mykhailenko** [comment]
Hello, we taking this to work and will review the process of throwing correct errors

**Comment by yanickrochon** [comment]
What is the resolution for this? I have followed the tutorial, and testing to send an email does nothing. No errors, no logs.

**Comment by netdelight** [comment]
Same here, no error, but no actual mail sent either...
