### ISSUE TITLE
Set Mailjet Template

### ISSUE THREAD

**Issue by willyj87** [mailjet/laravel-mailjet#9]
Is there a way to set mailjet template and use template language?

**Comment by latanasov** [comment]
Hi @willyj87  you can work with templates through the `TemplateServiceProvider::class`. Take a look at the examples Storing&sending a template [here](https://mailjet.github.io/laravel-mailjet/usage/#storing-sending-a-template).

**Comment by willyj87** [comment]
Hi thank you very much. I am so excited to try.
